/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    sectors: Sector;
    productCategories: ProductCategory;
    documents: Document;
    jobOpenings: JobOpening;
    contactSubmissions: ContactSubmission;
    careerApplications: CareerApplication;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    productCategories: ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    jobOpenings: JobOpeningsSelect<false> | JobOpeningsSelect<true>;
    contactSubmissions: ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    careerApplications: CareerApplicationsSelect<false> | CareerApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    mainNav: MainNav;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    mainNav: MainNavSelect<false> | MainNavSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Tüm görseller, videolar ve PDF dosyaları. Buradan yüklediklerinizi sayfa bloklarından seçebilirsiniz.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Sitedeki tüm sayfaların içeriği. Her sayfa "Sayfa içeriği" altındaki bloklarla yönetilir. Her bloğun metni, görseli, butonu düzenlenebilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Admin panelinde gösterilen sayfa adı (ör. "Ana Sayfa", "Hakkımızda"). URL’i etkilemez.
   */
  title: string;
  /**
   * Sayfanın adresi. Ana sayfa için "home". Diğerleri için "hakkimizda", "kariyer", "iletisim" gibi. Politika alt sayfaları için "politikalarimiz/kalite" şeklinde.
   */
  slug: string;
  /**
   * Sayfanın Google ve sosyal medyada nasıl görüneceği. Boş bırakılan alanlar için sayfa başlığı/açıklaması kullanılır.
   */
  meta?: {
    /**
     * 50-60 karakter ideal. Boş bırakılırsa sayfa adı kullanılır. Site adı otomatik eklenir.
     */
    title?: string | null;
    /**
     * 150-160 karakter ideal. Google arama sonuçlarında görünür.
     */
    description?: string | null;
    /**
     * ör. kimya, yapı, gıda, holding, paşaoğlu
     */
    keywords?: string | null;
    /**
     * WhatsApp/Facebook/Twitter’da link paylaşıldığında görünen kapak. 1200x630 px önerilir.
     */
    image?: (number | null) | Media;
    /**
     * Sosyal paylaşımlar için ayrı başlık. Boşsa SEO başlığı kullanılır.
     */
    ogTitle?: string | null;
    /**
     * Sosyal paylaşımlar için ayrı açıklama.
     */
    ogDescription?: string | null;
    /**
     * Sayfanın resmi tek adresi. Yinelenen içerik problemini önler. ör. https://pasaoglugroup.com.tr/hakkimizda
     */
    canonicalUrl?: string | null;
    /**
     * İşaretlerseniz bu sayfa Google’da görünmez.
     */
    noindex?: boolean | null;
  };
  /**
   * Sayfaya bölümler ekleyin. "+ Bölüm Ekle" diyerek Hero, Görsel+Metin, İstatistik, Kart Grid, Akordeon vb. ekleyebilirsiniz.
   */
  layout: (
    | {
        variant?: ('centered' | 'sidePanel' | 'leftAligned' | 'fullImage') | null;
        eyebrow?: string | null;
        title: string;
        titleAccent?: string | null;
        description?: string | null;
        video?: (number | null) | Media;
        poster?: (number | null) | Media;
        buttons?:
          | {
              label: string;
              href: string;
              variant?: ('primary' | 'accent' | 'ghost') | null;
              id?: string | null;
            }[]
          | null;
        certifications?:
          | {
              name: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        sidePanel?: {
          panelTitle?: string | null;
          panelText?: string | null;
          panelCtaLabel?: string | null;
          panelCtaHref?: string | null;
        };
        showScrollIndicator?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroVideo';
      }
    | {
        mediaSide?: ('right' | 'left') | null;
        eyebrow?: string | null;
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        imageCaption?: string | null;
        features?:
          | {
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        button?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'splitTextImage';
      }
    | {
        variant?: ('dark' | 'light') | null;
        items?:
          | {
              value: string;
              label: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsGrid';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        columns?: ('2' | '3' | '4') | null;
        cards?:
          | {
              image?: (number | null) | Media;
              title: string;
              description?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureCards';
      }
    | {
        title?: string | null;
        logos?:
          | {
              logo: number | Media;
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'partnerMarquee';
      }
    | {
        title?: string | null;
        description?: string | null;
        documents?: (number | Document)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'documentGrid';
      }
    | {
        title?: string | null;
        description?: string | null;
        items?:
          | {
              title: string;
              body?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'accordion';
      }
    | {
        quote: string;
        author?: string | null;
        background?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quoteBand';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        title?: string | null;
        description?: string | null;
        categories?: (number | ProductCategory)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'productAccordion';
      }
    | {
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'policyNav';
      }
    | {
        sectionEyebrow?: string | null;
        sectionTitle: string;
        tabs?:
          | {
              title: string;
              body: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              detailHref?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'policyTabs';
      }
    | {
        title?: string | null;
        description?: string | null;
        milestones?:
          | {
              year: string;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'timeline';
      }
    | {
        title?: string | null;
        description?: string | null;
        columns?: ('2' | '3' | '4') | null;
        offices?:
          | {
              name: string;
              address: string;
              phone?: string | null;
              email?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'officeGrid';
      }
    | {
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        buttons?:
          | {
              label: string;
              href: string;
              variant?: ('gold' | 'ghost') | null;
              id?: string | null;
            }[]
          | null;
        variant?: ('dark' | 'light') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaBand';
      }
    | {
        title?: string | null;
        offices?:
          | {
              name: string;
              address: string;
              phone?: string | null;
              email?: string | null;
              mapEmbed?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactBlock';
      }
    | {
        title?: string | null;
        description?: string | null;
        departments?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'careerForm';
      }
    | {
        title?: string | null;
        subjects?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactForm';
      }
    | {
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        items?:
          | {
              date?: string | null;
              category?: string | null;
              image?: (number | null) | Media;
              title: string;
              excerpt?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'newsGrid';
      }
    | {
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        highlightPoints?:
          | {
              name?: string | null;
              xPercent: number;
              yPercent: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'worldReach';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * ISO sertifikaları, kalite belgeleri, MSDS/TDS gibi dosyalar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  category?: string | null;
  description?: string | null;
  cover?: (number | null) | Media;
  file: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kimya sayfasındaki ürün accordion’unda görünen kategoriler ve ürünler.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  icon?: string | null;
  description?: string | null;
  sortOrder?: number | null;
  subGroups?:
    | {
        title: string;
        products?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    quoteHref?: string | null;
    msdsHref?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Kimya, Yapı, Gıda sektör sayfaları. Her birinin renk teması ve içeriği bağımsız düzenlenebilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  /**
   * URL’deki ad (kimya, yapi, gida). Var olanı değiştirmeyin.
   */
  slug: string;
  shortDescription?: string | null;
  cardImage?: (number | null) | Media;
  theme: 'chem' | 'build' | 'food';
  /**
   * Sayfanın Google ve sosyal medyada nasıl görüneceği. Boş bırakılan alanlar için sayfa başlığı/açıklaması kullanılır.
   */
  meta?: {
    /**
     * 50-60 karakter ideal. Boş bırakılırsa sayfa adı kullanılır. Site adı otomatik eklenir.
     */
    title?: string | null;
    /**
     * 150-160 karakter ideal. Google arama sonuçlarında görünür.
     */
    description?: string | null;
    /**
     * ör. kimya, yapı, gıda, holding, paşaoğlu
     */
    keywords?: string | null;
    /**
     * WhatsApp/Facebook/Twitter’da link paylaşıldığında görünen kapak. 1200x630 px önerilir.
     */
    image?: (number | null) | Media;
    /**
     * Sosyal paylaşımlar için ayrı başlık. Boşsa SEO başlığı kullanılır.
     */
    ogTitle?: string | null;
    /**
     * Sosyal paylaşımlar için ayrı açıklama.
     */
    ogDescription?: string | null;
    /**
     * Sayfanın resmi tek adresi. Yinelenen içerik problemini önler. ör. https://pasaoglugroup.com.tr/hakkimizda
     */
    canonicalUrl?: string | null;
    /**
     * İşaretlerseniz bu sayfa Google’da görünmez.
     */
    noindex?: boolean | null;
  };
  layout: (
    | {
        variant?: ('centered' | 'sidePanel' | 'leftAligned' | 'fullImage') | null;
        eyebrow?: string | null;
        title: string;
        titleAccent?: string | null;
        description?: string | null;
        video?: (number | null) | Media;
        poster?: (number | null) | Media;
        buttons?:
          | {
              label: string;
              href: string;
              variant?: ('primary' | 'accent' | 'ghost') | null;
              id?: string | null;
            }[]
          | null;
        certifications?:
          | {
              name: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        sidePanel?: {
          panelTitle?: string | null;
          panelText?: string | null;
          panelCtaLabel?: string | null;
          panelCtaHref?: string | null;
        };
        showScrollIndicator?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroVideo';
      }
    | {
        mediaSide?: ('right' | 'left') | null;
        eyebrow?: string | null;
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        imageCaption?: string | null;
        features?:
          | {
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        button?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'splitTextImage';
      }
    | {
        variant?: ('dark' | 'light') | null;
        items?:
          | {
              value: string;
              label: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsGrid';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        columns?: ('2' | '3' | '4') | null;
        cards?:
          | {
              image?: (number | null) | Media;
              title: string;
              description?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureCards';
      }
    | {
        title?: string | null;
        logos?:
          | {
              logo: number | Media;
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'partnerMarquee';
      }
    | {
        title?: string | null;
        description?: string | null;
        documents?: (number | Document)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'documentGrid';
      }
    | {
        title?: string | null;
        description?: string | null;
        items?:
          | {
              title: string;
              body?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'accordion';
      }
    | {
        quote: string;
        author?: string | null;
        background?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quoteBand';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        title?: string | null;
        description?: string | null;
        categories?: (number | ProductCategory)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'productAccordion';
      }
    | {
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'policyNav';
      }
    | {
        sectionEyebrow?: string | null;
        sectionTitle: string;
        tabs?:
          | {
              title: string;
              body: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              detailHref?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'policyTabs';
      }
    | {
        title?: string | null;
        description?: string | null;
        milestones?:
          | {
              year: string;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'timeline';
      }
    | {
        title?: string | null;
        description?: string | null;
        columns?: ('2' | '3' | '4') | null;
        offices?:
          | {
              name: string;
              address: string;
              phone?: string | null;
              email?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'officeGrid';
      }
    | {
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        buttons?:
          | {
              label: string;
              href: string;
              variant?: ('gold' | 'ghost') | null;
              id?: string | null;
            }[]
          | null;
        variant?: ('dark' | 'light') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaBand';
      }
    | {
        title?: string | null;
        offices?:
          | {
              name: string;
              address: string;
              phone?: string | null;
              email?: string | null;
              mapEmbed?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactBlock';
      }
    | {
        title?: string | null;
        description?: string | null;
        departments?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'careerForm';
      }
    | {
        title?: string | null;
        subjects?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactForm';
      }
    | {
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        items?:
          | {
              date?: string | null;
              category?: string | null;
              image?: (number | null) | Media;
              title: string;
              excerpt?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'newsGrid';
      }
    | {
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        highlightPoints?:
          | {
              name?: string | null;
              xPercent: number;
              yPercent: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'worldReach';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Kariyer sayfasında listelenecek aktif iş ilanları.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobOpenings".
 */
export interface JobOpening {
  id: number;
  title: string;
  department: string;
  location?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  subject?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careerApplications".
 */
export interface CareerApplication {
  id: number;
  fullName: string;
  email: string;
  phone?: string | null;
  department: string;
  coverLetter?: string | null;
  cv?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'productCategories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'jobOpenings';
        value: number | JobOpening;
      } | null)
    | ({
        relationTo: 'contactSubmissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'careerApplications';
        value: number | CareerApplication;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  layout?:
    | T
    | {
        heroVideo?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              title?: T;
              titleAccent?: T;
              description?: T;
              video?: T;
              poster?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              certifications?:
                | T
                | {
                    name?: T;
                    description?: T;
                    id?: T;
                  };
              sidePanel?:
                | T
                | {
                    panelTitle?: T;
                    panelText?: T;
                    panelCtaLabel?: T;
                    panelCtaHref?: T;
                  };
              showScrollIndicator?: T;
              id?: T;
              blockName?: T;
            };
        splitTextImage?:
          | T
          | {
              mediaSide?: T;
              eyebrow?: T;
              title?: T;
              body?: T;
              image?: T;
              imageCaption?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              button?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsGrid?:
          | T
          | {
              variant?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureCards?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              columns?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partnerMarquee?:
          | T
          | {
              title?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        documentGrid?:
          | T
          | {
              title?: T;
              description?: T;
              documents?: T;
              id?: T;
              blockName?: T;
            };
        accordion?:
          | T
          | {
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBand?:
          | T
          | {
              quote?: T;
              author?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        productAccordion?:
          | T
          | {
              title?: T;
              description?: T;
              categories?: T;
              id?: T;
              blockName?: T;
            };
        policyNav?:
          | T
          | {
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        policyTabs?:
          | T
          | {
              sectionEyebrow?: T;
              sectionTitle?: T;
              tabs?:
                | T
                | {
                    title?: T;
                    body?: T;
                    detailHref?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              title?: T;
              description?: T;
              milestones?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        officeGrid?:
          | T
          | {
              title?: T;
              description?: T;
              columns?: T;
              offices?:
                | T
                | {
                    name?: T;
                    address?: T;
                    phone?: T;
                    email?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        contactBlock?:
          | T
          | {
              title?: T;
              offices?:
                | T
                | {
                    name?: T;
                    address?: T;
                    phone?: T;
                    email?: T;
                    mapEmbed?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        careerForm?:
          | T
          | {
              title?: T;
              description?: T;
              departments?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              subjects?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    date?: T;
                    category?: T;
                    image?: T;
                    title?: T;
                    excerpt?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        worldReach?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              highlightPoints?:
                | T
                | {
                    name?: T;
                    xPercent?: T;
                    yPercent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  cardImage?: T;
  theme?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  layout?:
    | T
    | {
        heroVideo?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              title?: T;
              titleAccent?: T;
              description?: T;
              video?: T;
              poster?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              certifications?:
                | T
                | {
                    name?: T;
                    description?: T;
                    id?: T;
                  };
              sidePanel?:
                | T
                | {
                    panelTitle?: T;
                    panelText?: T;
                    panelCtaLabel?: T;
                    panelCtaHref?: T;
                  };
              showScrollIndicator?: T;
              id?: T;
              blockName?: T;
            };
        splitTextImage?:
          | T
          | {
              mediaSide?: T;
              eyebrow?: T;
              title?: T;
              body?: T;
              image?: T;
              imageCaption?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              button?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsGrid?:
          | T
          | {
              variant?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureCards?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              columns?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partnerMarquee?:
          | T
          | {
              title?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        documentGrid?:
          | T
          | {
              title?: T;
              description?: T;
              documents?: T;
              id?: T;
              blockName?: T;
            };
        accordion?:
          | T
          | {
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBand?:
          | T
          | {
              quote?: T;
              author?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        productAccordion?:
          | T
          | {
              title?: T;
              description?: T;
              categories?: T;
              id?: T;
              blockName?: T;
            };
        policyNav?:
          | T
          | {
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        policyTabs?:
          | T
          | {
              sectionEyebrow?: T;
              sectionTitle?: T;
              tabs?:
                | T
                | {
                    title?: T;
                    body?: T;
                    detailHref?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              title?: T;
              description?: T;
              milestones?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        officeGrid?:
          | T
          | {
              title?: T;
              description?: T;
              columns?: T;
              offices?:
                | T
                | {
                    name?: T;
                    address?: T;
                    phone?: T;
                    email?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        contactBlock?:
          | T
          | {
              title?: T;
              offices?:
                | T
                | {
                    name?: T;
                    address?: T;
                    phone?: T;
                    email?: T;
                    mapEmbed?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        careerForm?:
          | T
          | {
              title?: T;
              description?: T;
              departments?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              subjects?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    date?: T;
                    category?: T;
                    image?: T;
                    title?: T;
                    excerpt?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        worldReach?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              highlightPoints?:
                | T
                | {
                    name?: T;
                    xPercent?: T;
                    yPercent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  description?: T;
  sortOrder?: T;
  subGroups?:
    | T
    | {
        title?: T;
        products?:
          | T
          | {
              name?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        quoteHref?: T;
        msdsHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  description?: T;
  cover?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobOpenings_select".
 */
export interface JobOpeningsSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careerApplications_select".
 */
export interface CareerApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  department?: T;
  coverLetter?: T;
  cv?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Logo, telefon, e-posta, sosyal medya ve footer kolonları — tüm sayfalarda görünür.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  tagline?: string | null;
  phone?: string | null;
  email?: string | null;
  addresses?:
    | {
        name: string;
        address: string;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform: 'linkedin' | 'instagram' | 'facebook' | 'youtube' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sayfaya özel meta verilmediğinde kullanılan varsayılanlar ve analitik entegrasyonları.
   */
  seo?: {
    siteName?: string | null;
    /**
     * %s sayfanın başlığıyla değiştirilir.
     */
    titleTemplate?: string | null;
    defaultDescription?: string | null;
    defaultOgImage?: (number | null) | Media;
    twitterHandle?: string | null;
    googleSiteVerification?: string | null;
    googleAnalyticsId?: string | null;
    organizationLegalName?: string | null;
  };
  footer?: {
    description?: string | null;
    columns?:
      | {
          title: string;
          links?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sitenin üst kısmındaki menü öğeleri ve alt menüleri.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mainNav".
 */
export interface MainNav {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  logoDark?: T;
  tagline?: T;
  phone?: T;
  email?: T;
  addresses?:
    | T
    | {
        name?: T;
        address?: T;
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        siteName?: T;
        titleTemplate?: T;
        defaultDescription?: T;
        defaultOgImage?: T;
        twitterHandle?: T;
        googleSiteVerification?: T;
        googleAnalyticsId?: T;
        organizationLegalName?: T;
      };
  footer?:
    | T
    | {
        description?: T;
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mainNav_select".
 */
export interface MainNavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}